config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Commontator::Engine => '/commontator'
  namespace :admin do
    resources :videos do
      resources :subtitles
      member do
        patch :encode
      end
      collection do
        get :featured
      end
    end
    resources :categories
    resources :photos do
      collection do
        get :featured
      end
    end
  end

  resources :categories, only: [:show] do
    member do
      get :tag
    end

    resources :videos, only: [:index]
  end

  resources :videos, only: [:show, :index] do
    collection do
      get :search
      get :most_viewed
      get :most_scored
      get :most_voted
    end
    member do
      get :download
      get :tag
      get :wide
      get :embed
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
      post :favorite
      post :unfavorite
      post :capture_photo
    end
  end

  resources :favorites, only: [:index]

  resources :subtitles do
    member do
      get :tag
      post :add_to_playlist
      post :remove_from_playlist
    end
  end

  resources :playlists do
    member do
      get :embed
    end
  end
  resources :plays
  resources :photos do
    member do
      get :tag
    end
    collection do
      get :search
      get :featured
    end
  end
  
  resources :users do
    member do
      get :photos
      get :videos
    end
  end

  get '/admin', to: 'admin/videos#index', as: 'admin_root'
  root to: "homes#index"
end

app/models/video.rb
require "redis"
class Video < ActiveRecord::Base
  acts_as_taggable
  acts_as_commontable
  acts_as_votable

  markable_as :favorite
  
  is_impressionable counter_cache: true
  
  mount_uploader :file, VideoFileUploader
  mount_uploader :thumbnail, VideoThumbnailUploader
  scope :recent, ->{ order(created_at: :desc) }
  scope :most_viewed, ->{ order('impressions_count DESC') }
  scope :most_scored, ->{ order('votes_score DESC') }
  scope :most_voted, ->{ order('upvotes_count DESC') }
  scope :featured, ->{ where(featured: true) }
  scope :encoded, ->{ where.not(status: 'encoding') }

  has_many :subtitles, -> { order('start_at ASC') }, dependent: :destroy
  belongs_to :category
  belongs_to :user
  has_one :play, as: :playable

  has_many :photos
  after_create :encode_video_file

  validates_presence_of :title

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  def update_meta_tags
    tags = self.tag_list || []
    tags << self.category.try(:name)
    self.meta_tags = (self.subtitles.map(&:title) + tags).join(', ')
    self.save
  end

  def refresh_metadata
    movie = FFMPEG::Movie.new(self.file.path)
    self.duration = movie.duration
    self.width = movie.width
    self.height = movie.height
    self.thumbnail = movie.screenshot("tmp/thumbnail-#{self.id}-#{seconds}.jpg", :seek_time => 10)
    self.save
  end

  def screen_shot_at(seconds)
    movie = FFMPEG::Movie.new(self.file.path)
    movie.screenshot("tmp/thumbnail-#{self.id}-#{seconds}.jpg", :seek_time => seconds)
  end

  def encoding_progress
    redis = Redis.new
    redis.get("video_encoding_progress_#{self.id}")
  end

  def self.encode(id)
    video = Video.find(id)
    if !video.playable? and video.status!='encoding'
      video.status = 'encoding'
      video.save

      movie = FFMPEG::Movie.new(video.file.path)
      file_extension = File.extname(video.file.path)
      file_name = File.basename(video.file.path, file_extension)
      new_file_name = "tmp/#{file_name}-#{Time.now.to_s(:number)}.mp4"
      redis = Redis.new
      video.file = movie.transcode(new_file_name) do |progress|
        redis.set("video_encoding_progress_#{id}", progress)
        puts progress
      end
      video.status = 'encoded'
      video.save
    end
  end

  def playable?
    if self.status=='encoding'
      return false
    elsif self.status=='encoded'
      return true
    end

    return false if !self.file?

    black_list = ['.vob', '.flv', '.ts']
    white_list = ['.mp4', '.m4v', '.webm', '.ogg', '.mov']
    return false unless white_list.include? File.extname(self.file.path).downcase

    movie = FFMPEG::Movie.new(self.file.path)
    codec = movie.video_codec || ""
    return true if codec.include?('h264')
    return false
  end

  def encode_video_file
    unless self.playable?
      Video.delay_for(10.seconds).encode(self.id)
    end
  end

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'description', 'meta_tags']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            title: {},
            description: {},
            meta_tags: {}
          }
        }
      }
    )
  end

end

Video.import

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_filter :set_video, only: [:edit, :update, :destroy, :encode]

  def index
    @videos = Video.recent.page(params[:page])
  end

  def new
    @video = Video.new
  end

  def tag
  end

  def featured
    @videos = Video.featured.recent.page(params[:page])
    render :index
  end

  def edit
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    if @video.save
      flash[:success] = "Created a video successfully."
      redirect_to admin_videos_path
    else
      render :edit
    end
  end

  def update
    if @video.update_attributes(video_params)
      flash[:success] = "Updated a video successfully."
      redirect_to edit_admin_video_path(@video)
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    flash[:success] = "Deleted a video successfully."
    redirect_to admin_videos_path
  end

  def encode
    flash[:success] = "Started to encode a video successfully. Wait several minutes."
    Video.delay.encode(@video.id)
    redirect_to edit_admin_video_path(@video)
  end

  private
  def video_params
    params.require(:video).permit(:title, :description, :file, :thumbnail, :tag_list, :category_id, :featured)
  end

  def set_video
    @video = Video.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :set_category, :set_most_viewed
  impressionist :actions=>[:show]

  before_filter :set_sort_and_filter
  before_filter :set_subtitle

  before_filter :authenticate_user!, only: [:favorite, :unfavorite]
  layout :set_wide_layout, only: [:wide]

  def show
    @video = Video.find(params[:id])
    @video.impressions_count = @video.impressionist_count
    @video.save
  end
  
  def tag_cloud
    @tags = Video.tag_counts_on(:tags)
  end

  def index
    if !params[:tag].blank?
      @videos = Video.tagged_with(params[:tag])
    else
      if @sort_by
        @videos = Video.order("#{@sort_by} #{@sort_direction}")
      else
        @videos = Video.recent
      end
    end

    @videos = @videos.where(category_id: @category.id) if !@category.blank?
    @videos = @videos.where("created_at >= ?", @start_date) if @start_date
    @videos = @videos.where("created_at <= ?", @end_date) if @end_date
    @videos = @videos.page(params[:page]).per(12)
  end

  def search
    @videos = Video.search(params[:search])
    @videos = @videos.page(params[:page])
  end

  def most_viewed
    @title = "Most viewed"
    @videos = Video.most_viewed.page(params[:page])
    render :index
  end

  def most_voted
    @title = "Recommended"
    @videos = Video.most_voted.page(params[:page])
    render :index
  end

  def most_scored
    @title = "Top videos"
    @videos = Video.most_scored.page(params[:page])
    render :index
  end

  def tag
    @videos = Video.tagged_with(params[:id])
    @videos = @videos.order("#{@sort_by} #{@sort_direction}") if @sort_by
    @videos = @videos.page(params[:page])
    @tag = params[:id]
    render :index
  end

  def download
    @video = Video.find(params[:id])
    redirect_to @video.file.url
  end

  def upvote
    @video = Video.find(params[:id])
    @video.upvote_by current_user
    @video.upvotes_count = @video.get_upvotes.count
    @video.votes_score = @video.upvotes_count - @video.downvotes_count
    @video.save
    redirect_to video_path(@video)
  end

  def downvote
    @video = Video.find(params[:id])
    @video.downvote_by current_user
    @video.downvotes_count = @video.get_downvotes.count
    @video.votes_score = @video.upvotes_count - @video.downvotes_count
    @video.save
    redirect_to video_path(@video)
  end

  def favorite
    @video = Video.find(params[:id])
    current_user.favorite_videos << @video
    current_user.save
    flash[:success] = "Added a video to favorites successfully."
    if params[:redirect]
      redirect_to params[:redirect]
    else
      redirect_to video_path(@video)
    end
  end

  def unfavorite
    @video = Video.find(params[:id])
    current_user.favorite_videos.delete @video
    flash[:success] = "Removed a video from favorites successfully."

    if params[:redirect]
      redirect_to params[:redirect]
    else
      redirect_to video_path(@video)
    end
  end

  def wide
    @video = Video.find(params[:id])

  end

  def set_wide_layout
    'wide'
  end

  def capture_photo
    @video = Video.find(params[:id])
    if !params[:video_at].blank?
      @photo = Photo.new
      @photo.file = @video.screen_shot_at(params[:video_at].to_f)
      @photo.title = "#{@video.title} #{Time.now.to_f}"
      @photo.video_at = params[:video_at].to_i
      @photo.video = @video
      @photo.user = current_user
      @photo.save

      redirect_to edit_admin_photo_path(@photo)
    else
      redirect_to :back
    end
  end

  def embed
    @video = Video.find(params[:id])
    render :embed, layout: 'embed'
  end

  private
  def set_category
    @category = Category.find(params[:category_id]) rescue nil
  end

  def set_most_viewed
    @most_viewed = Video.order('impressions_count DESC').take(10)
  end

  def set_sort_and_filter
    @sort_by = params[:sort_by]
    @sort_direction = params[:sort_direction] || 'desc'

    @start_date = Time.parse(params[:start_date]) rescue nil
    @end_date = Time.parse(params[:end_date]) rescue nil
  end

  def set_subtitle
    @subtitle = Subtitle.find(params[:subtitle_id]) if params[:subtitle_id]
  end
end

app/views/videos/_list.html.haml
- @videos.each_with_index do |video, index|
  .item.video
    .row
      .col-sm-2
        = link_to embed_video_path(video.id) + '#title', class: 'img-video', rel: 'video' do
          - if video.thumbnail?
            = image_tag video.thumbnail.thumb.url, class: "img-responsive thumbnail", alt: video.title
          - else
            = image_tag asset_path('no-thumbnail.png'), class: "img-responsive thumbnail", alt: video.title
        
      .col-sm-10
        %h4.title
          = link_to video_path(video.id) + '#title' do
            - if video.marked_as? :favorite, :by => current_user
              %span.glyphicon.glyphicon-star-empty
            = video.title
        %p
          %small.text-primary
            %span.glyphicon.glyphicon-thumbs-up
            = video.get_upvotes.count
          &nbsp;
          %small.text-danger
            %span.glyphicon.glyphicon-thumbs-down
            = video.get_downvotes.count
          &nbsp;
          %small
            %span.glyphicon.glyphicon-time
            = Time.at(video.duration).utc.strftime("%H:%M:%S")
          &nbsp;
          %small
            %span.glyphicon.glyphicon-tags
            - if video.tags.count > 0
              = video.tag_list
            - else
              NONE
          &nbsp;
          %small
            %span.glyphicon.glyphicon-file
            = time_ago_in_words(video.created_at)
            ago
          &nbsp;
          - if video.user
            = link_to user_path(video.user) do
              %small
                %span.glyphicon.glyphicon-user
                #{video.user.full_name}
            &nbsp;
          - else
            %small
              %span.glyphicon.glyphicon-user
              Unknown
            &nbsp;
          - if video.subtitles.count > 0
            %small
              %span.glyphicon.glyphicon-list
              = video.subtitles.count
              subtitles
          %small
            %span.glyphicon.glyphicon-eye-open
            = video.impressionist_count
            visits (today #{video.impressionist_count(:start_date=>Time.now.strftime("%Y-%m-%d"))})

          &nbsp;
        %p
          - video.subtitles.each do |subtitle|
            - video = subtitle.video
            |
            = link_to video_path(video, subtitle_id: subtitle.id) do
              = subtitle.title
        %p
          - unless video.marked_as? :favorite, :by => current_user
            = link_to favorite_video_path(video), method: :post, class: 'btn btn-warning btn-xs' do
              %span.glyphicon.glyphicon-star

          = link_to edit_admin_video_path(video) + '#title', class: 'btn btn-primary btn-xs' do
            %span.glyphicon.glyphicon-pencil
        %p
          = sanitize(truncate(video.description, :omission => "...", :length => 40))

app/views/videos/_video.html.haml
.video
  = link_to embed_video_path(video), class: 'img-video', rel: 'video' do
    - if video.thumbnail?
      = image_tag video.thumbnail.thumb.url, class: "img-responsive thumbnail", alt: video.title
    - else
      = image_tag asset_path('no-thumbnail.png'), class: "img-responsive thumbnail", alt: video.title

  %h4.title
    = link_to video_path(video) do
      = video.title
  %p
    %small
      %span.glyphicon.glyphicon-time
      = Time.at(video.duration).utc.strftime("%H:%M:%S")
    %br

    - if video.user
      = link_to user_path(video.user) do
        %small
        %span.glyphicon.glyphicon-user
        = video.user.full_name
      %br
    
    %small
      %span.glyphicon.glyphicon-file
      Posted
      = time_ago_in_words(video.created_at)
      ago
    %br

    %small
      = video.subtitles.count
      subtitles
  %p
    = sanitize(truncate(video.description, :omission => "...", :length => 40))

app/views/videos/index.html.haml
- content_for :sidebar do
  = render 'sidebar'
- content_for :before_content do
  #carousel.visible-sm.visible-md.visible-lg
    .slideshow{ :"data-cycle" => { fx: 'carousel', timeout: 3000, slides: '>a' } }
      - Video.featured.take(12).to_a.shuffle.each do |video|
        = link_to video_path(video) do
          = image_tag video.thumbnail.thumb.url, title: video.title
          %span.subtitle
            = truncate(video.title, :omission => "...", :length => 12)
- content_for :search_box do
  .clearfix
    .pull-right
      = bootstrap_form_tag url: search_videos_path, method: :get, layout: :inline do |f|
        = f.text_field :search, hide_label: true, placeholder: 'Search videos'
        = f.button :search, class: 'btn btn-info' do
          %span.glyphicon.glyphicon-search
          Search
.clearfix
  - if @title
    %h4
      = @title
  - if @category
    %h4
      %span.glyphicon.glyphicon-folder-open
      &nbsp;
      =@category.name

  - if @tag
    %h4
      %span.glyphicon.glyphicon-tags
      &nbsp;
      = @tag
  - if params[:search]
    %h4
      %span.glyphicon.glyphicon-search
      &nbsp;
      = params[:search]


- if @videos.count > 0
  #gallery
    = render 'list'
    .clearfix
      = paginate @videos
- else
  .row
    .alert.alert-warning
      Sorry, There is no matched videos.

:javascript
  $(function(){
    $('#gallery').photobox('a.img-video',{ time:1000, zoomable: false, loop: false});
  });
  

app/views/videos/show.html.haml
- content_for :sidebar do
  = render 'sidebar'

:javascript
  var subtitles = #{@video.subtitles.to_json};
  var video = #{@video.to_json};
  var current_subtitle_index = null;
  var currentSubtitle = null;
  var start_at = 0;
  var repeat = false

  var seekToVideo = function seekToVideo(index, rep){
    repeat = rep

    var subtitle = $('#subtitle_' + index);
    currentSubtitle = subtitles[index];
    updateCurrentSubtitleHtml(currentSubtitle);
    $('#movie').get(0).currentTime = currentSubtitle.start_at;
    $('.repeat .text').html('');
    if(rep){
      $('.repeat .text', subtitle).html('<small>repeating...</small>');
    }else{
      $('.repeat .text', subtitle).html('');
    }
  }

  var updateCurrentSubtitleHtml = function(subtitle){
    if(subtitle){
      $('#subtitle').html(subtitle.title);
      if(subtitle.description){
        var description = subtitle.description.replace(/(?:\r\n|\r|\n)/g, '<br />')
        $('#description').html(description);
      }else{
        $('#description').html(video.description);
      }
    }
  }

  var getCurrentSubtitle = function(subtitles, currentTime){
    for(var i=0;i<subtitles.length;i++){
      if(currentTime > subtitles[i].start_at && currentTime < subtitles[i].end_at){
        return subtitles[i];
      }
    }
    return {};
  }

  $(function(){
    var movie = $('#movie').get(0);
    for(var i=0;i<subtitles.length;i++){
      if (subtitles[i+1]){
        subtitles[i].end_at = subtitles[i].end_at || subtitles[i+1].start_at;
      }else{
        subtitles[i].end_at = subtitles[i].end_at || 9999999999;
      }
    }

    $(movie).bind('timeupdate', function() {
      if(currentSubtitle && movie.currentTime > currentSubtitle.end_at && repeat==true){
        movie.currentTime = currentSubtitle.start_at;
      }

      subtitle = getCurrentSubtitle(subtitles, movie.currentTime);
      updateCurrentSubtitleHtml(subtitle);
    })

    // display comments at start
    $('.thread a').trigger('click');

    // seek when press arrow keys
    var frameTime = 5;
    window.addEventListener('keydown', function (evt) {
      if (true) { //or you can force it to pause here
          if (evt.keyCode === 37) { //left arrow
              if (movie.currentTime > 0) {
                  //one frame back
                  movie.currentTime -= frameTime;
              }
          } else if (evt.keyCode === 39) { //right arrow

              if (movie.currentTime < movie.duration) {
                  //one frame forward
                  //Don't go past the end, otherwise you may get an error
                  movie.currentTime = Math.min(movie.duration, movie.currentTime + frameTime);
              }
          }
      }
    });
  });

  function captureSubtitlePosition(){
    $('#movie').get(0).pause();
    $('#video_at').val($('#movie').get(0).currentTime);
    if (confirm('Are you sure?')){
      $('#photo_form').submit();
    }
  }

.row
  .col-sm-12
    %h3#title
      =@video.title
    %p
      = link_to like_video_path(@video), method: :put, class: 'btn btn-primary btn-sm' do
        %span.glyphicon.glyphicon-thumbs-up
        Like
        = "( #{@video.get_upvotes.size} )"
      &nbsp;

      = link_to dislike_video_path(@video), method: :put, class: 'btn btn-danger btn-sm' do
        %span.glyphicon.glyphicon-thumbs-down
        Dislike
        = "( #{@video.get_downvotes.size} )"
      &nbsp;

      - if @video.marked_as? :favorite, :by => current_user
        = link_to unfavorite_video_path(@video), method: :post, class: 'btn btn-danger btn-sm' do
          %span.glyphicon.glyphicon-star-empty
          Unfavorite
      - else
        = link_to favorite_video_path(@video), method: :post, class: 'btn btn-warning btn-sm' do
          %span.glyphicon.glyphicon-star
          Favorite
      &nbsp;

      = link_to download_video_path(@video) do
        %span.glyphicon.glyphicon-download-alt
        Download
      &nbsp;

      = link_to edit_admin_video_path(@video) do
        %span.glyphicon.glyphicon-edit
        Edit

      .glyphicon.glyphicon-time
      = Time.at(@video.duration).utc.strftime("%H:%M:%S")
      &nbsp;

      - if @video.user
        %small
          %span.glyphicon.glyphicon-user
          Posted by #{@video.user.email}
        &nbsp;

      %small
        %span.glyphicon.glyphicon-file
        = time_ago_in_words(@video.created_at)
        ago

      &nbsp;
      %small
        %span.glyphicon.glyphicon-eye-open
        = @video.impressionist_count
        visits (today #{@video.impressionist_count(:start_date=>Time.now.strftime("%Y-%m-%d"))})

      
    .row
      .col-sm-12
        %p
          %video#movie{:controls => "", :height => "auto", :poster => @video.thumbnail.url, :preload => "none", :width => "#{(@video.width < 1024 and @video.width>0)? @video.width.to_s + "px" : "100%" rescue "100%"}", :autoplay=> true}
            %source{:src => @video.file.url, :type => "video/mp4"}

        = form_tag capture_photo_video_path(@video), id: 'photo_form' do
          = hidden_field_tag :video_at
          %p
            = link_to "javascript: void(0); captureSubtitlePosition();", class: 'btn btn-primary', method: :post do
              %span.glyphicon.glyphicon-camera
              Capture And Post Photo


        %h4#subtitle
          =@subtitle.try(:title)
        #description
          = sanitize(simple_format(@video.description))
        %hr
    - if @video.subtitles.count > 0
      .row
        .col-sm-12
          .row
            - @video.subtitles.each_with_index do |subtitle, index|
              .col-md-2.col-sm-3.col-xs-3
                %div{ id: "subtitle_#{index}"}
                  - if subtitle.id == @subtitle.try(:id)
                    :javascript
                      setTimeout(function(){ seekToVideo(#{index}, false); }, 500);
                  %p
                    = link_to "#title", onclick: "seekToVideo(#{index}, false);" do
                      = image_tag subtitle.thumbnail.thumb.url, class: 'img-responsive'
                  %p.text-center
                    =link_to '#title', onclick: "seekToVideo(#{index}, !repeat);", class: 'repeat btn btn-xs' do
                      %span.glyphicon.glyphicon-repeat
                      %span.text
                    - unless (current_user && current_user.playlist && current_user.playlist.plays.include?(subtitle.play))
                      =link_to add_to_playlist_subtitle_path(subtitle), method: :post do
                        %span.glyphicon.glyphicon-plus
                        playlist
                    %br
                    %small
                      = Time.at((subtitle.end_at||subtitle.video.duration) - subtitle.start_at).utc.strftime("%H:%M:%S")
                    %br
                    %small
                      =subtitle.title
                      =link_to edit_admin_video_subtitle_path(subtitle.video, subtitle) do
                        %span.glyphicon.glyphicon-edit
              - if (index+1)%6==0
                .clearfix
    
      %hr
    .clearfix
      = commontator_thread(@video)
%br

app/views/videos/wide.html.haml
:javascript
  var subtitles = #{@video.subtitles.to_json};
  var video = #{@video.to_json};
  var current_subtitle_index = null;
  var currentSubtitle = null;
  var start_at = 0;
  var repeat = false

  var seekToVideo = function seekToVideo(index, rep){
    repeat = rep

    var subtitle = $('#subtitle_' + index);
    currentSubtitle = subtitles[index];
    updateCurrentSubtitleHtml(currentSubtitle);
    $('#movie').get(0).currentTime = currentSubtitle.start_at;

    $('.repeat .text').html('');
    if(rep){
      $('.repeat .text', subtitle).html('<small>repeating...</small>');
    }else{
      $('.repeat .text', subtitle).html('');
    }
  }

  var updateCurrentSubtitleHtml = function(subtitle){
    if(subtitle){
      $('#subtitle').html(subtitle.title);
      if(subtitle.description){
        var description = subtitle.description.replace(/(?:\r\n|\r|\n)/g, '<br />')
        $('#description').html(description);
      }else{
        $('#description').html(video.description);
      }
    }
  }

  var getCurrentSubtitle = function(subtitles, currentTime){
    for(var i=0;i<subtitles.length;i++){
      if(currentTime > subtitles[i].start_at && currentTime < subtitles[i].end_at){
        return subtitles[i];
      }
    }
    return {};
  }

  $(function(){
    var movie = $('#movie').get(0);
    for(var i=0;i<subtitles.length;i++){
      if (subtitles[i+1]){
        subtitles[i].end_at = subtitles[i].end_at || subtitles[i+1].start_at;
      }else{
        subtitles[i].end_at = subtitles[i].end_at || 9999999999;
      }
    }

    $(movie).bind('timeupdate', function() {
      if(currentSubtitle && movie.currentTime > currentSubtitle.end_at && repeat==true){
        movie.currentTime = currentSubtitle.start_at;
      }

      subtitle = getCurrentSubtitle(subtitles, movie.currentTime);
      updateCurrentSubtitleHtml(subtitle);
    })

    // display comments at start
    $('.thread a').trigger('click');
  });
.row
  .col-sm-12
    %h3#title
      =@video.title
    %p
      = link_to like_video_path(@video), method: :put, class: 'btn btn-primary btn-sm' do
        %span.glyphicon.glyphicon-thumbs-up
        Like
        = "( #{@video.get_upvotes.size} )"
      &nbsp;

      = link_to dislike_video_path(@video), method: :put, class: 'btn btn-danger btn-sm' do
        %span.glyphicon.glyphicon-thumbs-down
        Dislike
        = "( #{@video.get_downvotes.size} )"
      &nbsp;

      - if @video.marked_as? :favorite, :by => current_user
        = link_to unfavorite_video_path(@video), method: :post, class: 'btn btn-danger btn-sm' do
          %span.glyphicon.glyphicon-star-empty
          Unfavorite
      - else
        = link_to favorite_video_path(@video), method: :post, class: 'btn btn-warning btn-sm' do
          %span.glyphicon.glyphicon-star
          Favorite
      &nbsp;

      = link_to download_video_path(@video) do
        %span.glyphicon.glyphicon-download-alt
        Download
      &nbsp;

      = link_to edit_admin_video_path(@video) do
        %span.glyphicon.glyphicon-pencil
        Edit

      .glyphicon.glyphicon-time
      = Time.at(@video.duration).utc.strftime("%H:%M:%S")
      &nbsp;

      - if @video.user
        %small
          %span.glyphicon.glyphicon-user
          Posted by #{@video.user.email}
        &nbsp;

      %small
        %span.glyphicon.glyphicon-file
        = time_ago_in_words(@video.created_at)
        ago

      &nbsp;
      %small
        %span.glyphicon.glyphicon-eye-open
        = @video.impressionist_count
        visits (today #{@video.impressionist_count(:start_date=>Time.now.strftime("%Y-%m-%d"))})
.row
  .col-sm-6
    %video#movie{:controls => "", :height => "auto", :poster => @video.thumbnail.url, :preload => "none", :width => "100%", :autoplay=> true}
      %source{:src => @video.file.url, :type => "video/mp4"}
    - if @subtitle
      %h4#subtitle
        =@subtitle.title
    .row
      - @video.subtitles.each_with_index do |subtitle, index|
        .col-sm-2.col-xs-4
          %div{ id: "subtitle_#{index}"}
            - if subtitle.id == @subtitle.try(:id)
              :javascript
                seekToVideo(#{index}, false);

            = link_to "#title", onclick: "seekToVideo(#{index}, false);" do
              = image_tag subtitle.thumbnail.thumb.url, class: 'img-responsive'
            %p
              %small
                =subtitle.title
              %br
              %small
                = Time.at(subtitle.start_at).utc.strftime("%H:%M:%S")
              %br
              =link_to '#title', onclick: "seekToVideo(#{index}, !repeat);", class: 'repeat' do
                %span.glyphicon.glyphicon-repeat
                %span.text

        - if (index+1)%6==0
          .clearfix
        
  .col-sm-6
    #description
      = sanitize(simple_format(@video.description))

    %br
    %br
= commontator_thread(@video)
%br