config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Commontator::Engine => '/commontator'
  namespace :admin do
    resources :videos do
      resources :subtitles
      member do
        patch :encode
      end
      collection do
        get :featured
      end
    end
    resources :categories
    resources :photos do
      collection do
        get :featured
      end
    end
  end

  resources :categories, only: [:show] do
    member do
      get :tag
    end

    resources :videos, only: [:index]
  end

  resources :videos, only: [:show, :index] do
    collection do
      get :search
      get :most_viewed
      get :most_scored
      get :most_voted
    end
    member do
      get :download
      get :tag
      get :wide
      get :embed
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
      post :favorite
      post :unfavorite
      post :capture_photo
    end
  end

  resources :favorites, only: [:index]

  resources :subtitles do
    member do
      get :tag
      post :add_to_playlist
      post :remove_from_playlist
    end
  end

  resources :playlists do
    member do
      get :embed
    end
  end
  resources :plays
  resources :photos do
    member do
      get :tag
    end
    collection do
      get :search
      get :featured
    end
  end
  
  resources :users do
    member do
      get :photos
      get :videos
    end
  end

  get '/admin', to: 'admin/videos#index', as: 'admin_root'
  root to: "homes#index"
end

app/views/shared/_footer.html.haml
%footer
  .container
    %p.text-center
      Copyright @ 2015 Wetube Inc. All rights reserved.

app/views/shared/_header.html.haml
.navbar.navbar-inverse
  .navbar-header
    %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "WeTube", "/", class: 'navbar-brand'
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li{class: "#{'active' if controller_name == 'videos'}"}
        = link_to videos_path do
          %span.glyphicon.glyphicon-film
          Videos
      %li{class: "#{'active' if controller_name == 'subtitles'}"}
        = link_to subtitles_path do
          %span.glyphicon.glyphicon-subtitles
          Subtitles
      %li{class: "#{'active' if controller_name == 'playlists'}"}
        - if current_user
          -if current_user.playlist
            = link_to playlist_path(current_user.playlist) do
              %span.glyphicon.glyphicon-play
              Playlist
          - else
            = link_to playlists_path, method: :post do
              %span.glyphicon.glyphicon-play
              Playlist
        - else
          = link_to playlists_path do
            %span.glyphicon.glyphicon-play
            Playlist
      %li{class: "#{'active' if controller_name == 'favorites'}"}
        = link_to favorites_path do
          %span.glyphicon.glyphicon-star
          Favorites
      %li{class: "#{'active' if controller_name == 'photos'}"}
        = link_to photos_path do
          %span.glyphicon.glyphicon-picture
          Photos
      

    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to new_admin_video_path do
          %span.glyphicon.glyphicon-file
          New Video
      %li
        = link_to new_admin_photo_path do
          %span.glyphicon.glyphicon-file
          New Photo

      - if user_signed_in?
        %li
          = link_to edit_user_registration_path do
            %span.glyphicon.glyphicon-user
            #{current_user.full_name}
        %li
          = link_to destroy_user_session_path, method: :delete do
            %span.glyphicon.glyphicon-off
            Logout
      - else
        %li
          = link_to new_user_session_path do
            %span.glyphicon.glyphicon-log-in
            Login / Register

app/views/shared/_recent.html.haml
#recent
  %h3.page-title RECENT VIDEOS
  .row
    - Video.recent[0..3].each do |video|
      .col-sm-3
        = link_to video_path(video.id) do
          - if video.thumbnail?
            = image_tag video.thumbnail.thumb.url, class: "img-responsive"
          - else
            = image_tag asset_path('no-thumbnail.png'), class: "img-responsive"
        %h4
          = link_to video_path(video.id) do
            = video.title
        %p
          .glyphicon.glyphicon-time
          = Time.at(video.duration).utc.strftime("%H:%M:%S")

          %br
          
          %small
            %span.glyphicon.glyphicon-file
            Posted
            = time_ago_in_words(video.created_at)
            ago
        %p
          = sanitize(truncate(video.description, :omission => "...", :length => 40))

app/views/shared/_recent_subtitles.html.haml
#recent
  %h3.page-title SUBTITLES
  .row
    - subtitles = Subtitle.where(video_id: @videos.map(&:id)).recent[0..3] rescue Subtitle.recent[0..3]
    - if subtitles.count > 0
      - subtitles.each do |subtitle|
        - video = subtitle.video
        .col-sm-3.col-xs-6
          = link_to video_path(video, subtitle_id: subtitle.id) do
            - if video.thumbnail?
              = image_tag subtitle.thumbnail.thumb.url, class: "img-responsive"
            - else
              = image_tag asset_path('no-thumbnail.png'), class: "img-responsive"
          %h4
            = link_to video_path(video, subtitle_id: subtitle.id) do
              = subtitle.title
          %p
            %small
              %span.glyphicon.glyphicon-film
              = subtitle.video.title
            %br

            %small
              %span.glyphicon.glyphicon-time
              = Time.at(video.duration).utc.strftime("%H:%M:%S")

            %br
            
            %small
              %span.glyphicon.glyphicon-file
              Posted
              = time_ago_in_words(subtitle.created_at)
              ago
          %p
            = sanitize(truncate(video.description, :omission => "...", :length => 40))
    - else
      .alert.alert-warning
        There is no matched subtitles.

app/views/shared/_sidebar.html.haml
= yield :sidebar