config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Commontator::Engine => '/commontator'
  namespace :admin do
    resources :videos do
      resources :subtitles
      member do
        patch :encode
      end
      collection do
        get :featured
      end
    end
    resources :categories
    resources :photos do
      collection do
        get :featured
      end
    end
  end

  resources :categories, only: [:show] do
    member do
      get :tag
    end

    resources :videos, only: [:index]
  end

  resources :videos, only: [:show, :index] do
    collection do
      get :search
      get :most_viewed
      get :most_scored
      get :most_voted
    end
    member do
      get :download
      get :tag
      get :wide
      get :embed
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
      post :favorite
      post :unfavorite
      post :capture_photo
    end
  end

  resources :favorites, only: [:index]

  resources :subtitles do
    member do
      get :tag
      post :add_to_playlist
      post :remove_from_playlist
    end
  end

  resources :playlists do
    member do
      get :embed
    end
  end
  resources :plays
  resources :photos do
    member do
      get :tag
    end
    collection do
      get :search
      get :featured
    end
  end
  
  resources :users do
    member do
      get :photos
      get :videos
    end
  end

  get '/admin', to: 'admin/videos#index', as: 'admin_root'
  root to: "homes#index"
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_and_belongs_to_many :plays
  belongs_to :user
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_filter :authenticate_user!, only: [:create]
  
  def index
    @playlists = Playlist.all
  end

  def create
    @playlist = current_user.create_playlist(name: current_user.full_name)
    redirect_to playlist_path(@playlist)
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def embed
    @playlist = Playlist.find(params[:id])
    render :embed, layout: 'embed'
  end
  
end

app/views/playlists/_playlist.html.haml
- subtitle = playlist.plays.first.playable
- video = subtitle.video
.video
  = link_to embed_playlist_path(playlist), class: 'img-video', rel: 'video' do
    - if video.thumbnail?
      = image_tag subtitle.thumbnail.thumb.url, class: "img-responsive thumbnail", alt: subtitle.title
    - else
      = image_tag asset_path('no-thumbnail.png'), class: "img-responsive", alt: subtitle.title
  
  %h4.title
    = link_to playlist_path(playlist) do
      = subtitle.title
  %p
    %small
      %span.glyphicon.glyphicon-film
      = subtitle.video.title
    %br

    - if playlist.user
      = link_to user_path(playlist.user) do
        %small
        %span.glyphicon.glyphicon-user
        = playlist.user.full_name
      %br

    %small
      %span.glyphicon.glyphicon-time
      = Time.at((subtitle.end_at||subtitle.video.duration) - subtitle.start_at).utc.strftime("%H:%M:%S")

    %br
    
    %small
      %span.glyphicon.glyphicon-file
      Posted
      = time_ago_in_words(subtitle.created_at)
      ago
  %p
    = sanitize(truncate(video.description, :omission => "...", :length => 40))

app/views/playlists/embed.html.haml
%h3.page-title PLAYLIST
%h4 #{@playlist.name}
- if @playlist.plays.count > 0
  - #ActiveModel::Serializer.serializer_for(@playlist.plays.map(&:playable)).new(@playlist.plays.map(&:playable)).to_json
  - plays = @playlist.plays.shuffle
  :javascript
    var subtitles = #{plays.map(&:playable).to_json};
    var videos = #{plays.map(&:video).to_json};
    var current_subtitle_index = null;
    var currentPlay = null;
    var start_at = 0;
    var repeat = false

    var seekToVideo = function seekToVideo(index, rep){
      repeat = rep
      
      var subtitle = $('#subtitle_' + index);
      current_subtitle_index = index;
      currentSubtitle = subtitles[index];


      var player = $('#movie').get(0);
      var source = $('source', player);

      if ($(source).attr('src')!=videos[index].file.url){
        $(source).attr('src', videos[index].file.url);
        player.load();
        player.play();
      }
      
      $('#movie').get(0).currentTime = currentSubtitle.start_at;

      updateCurrentSubtitleHtml(currentSubtitle);
      $('.repeat .text').html('');
      if(rep){
        $('.repeat .text', subtitle).html('<small>repeating...</small>');
      }else{
        $('.repeat .text', subtitle).html('');
      }
    }

    var updateCurrentSubtitleHtml = function(subtitle){
      if(subtitle){
        $('#subtitle').html(subtitle.title);
        if(subtitle.description){
          var description = subtitle.description.replace(/(?:\r\n|\r|\n)/g, '<br />')
          $('#description').html(description);
        }else{
          $('#description').html('');
        }
      }
    }

    $(function(){
      var movie = $('#movie').get(0);
      var video = $('#movie').get(0);
      for(var i=0;i<subtitles.length;i++){
        subtitles[i].end_at = subtitles[i].end_at || videos[i].duration - 5;
      }

      $(movie).bind('timeupdate', function() {
        if (currentSubtitle){
          if (movie.currentTime > currentSubtitle.start_at && movie.currentTime > currentSubtitle.end_at && !repeat){
            seekToVideo((current_subtitle_index + 1)%subtitles.length, false);
          }
        }

        if(currentSubtitle && movie.currentTime > currentSubtitle.end_at && repeat==true){
          movie.currentTime = currentSubtitle.start_at;
        }
      })

      // display comments at start
      $('.thread a').trigger('click');

      // seek when press arrow keys
      var frameTime = 5;
      window.addEventListener('keydown', function (evt) {
        if (true) { //or you can force it to pause here
            if (evt.keyCode === 32) { //left arrow
              movie.pause();
              evt.preventDefault();
              return;
            }

            if (evt.keyCode === 37) { //left arrow
                if (movie.currentTime > 0) {
                    //one frame back
                    movie.currentTime -= frameTime;
                }
            } else if (evt.keyCode === 39) { //right arrow

                if (movie.currentTime < movie.duration) {
                    //one frame forward
                    //Don't go past the end, otherwise you may get an error
                    movie.currentTime = Math.min(movie.duration, movie.currentTime + frameTime);
                }
            }
        }
      });
      
      // play first video as default
      seekToVideo(0, false);
    });
  .row
    .col-sm-6
      %video#movie{:controls => "", :height => "auto", :poster => @playlist.plays.first.playable.thumbnail.url, :preload => "none", :width => "100%", :autoplay=> true}
        %source{:src => '', :type => "video/mp4"}

      %h4#subtitle
        =@subtitle.try(:title)
      #description
        = sanitize(simple_format(@subtitle.try(:description)))  
    .col-sm-6
      .row
        - plays.map(&:playable).each_with_index do |subtitle, index|
          .col-md-4.col-sm-4.col-xs-4
            %div{ id: "subtitle_#{index}"}
              %p
                = link_to "#title", onclick: "seekToVideo(#{index}, false);" do
                  = image_tag subtitle.thumbnail.thumb.url, class: 'img-responsive'
              %p.text-center
                =link_to '#title', onclick: "seekToVideo(#{index}, !repeat);", class: 'repeat btn btn-xs' do
                  %span.glyphicon.glyphicon-repeat
                  %span.text
                - if current_user && current_user.playlist.plays.include?(subtitle.play)
                  =link_to play_path(subtitle.play), method: :delete do
                    %span.glyphicon.glyphicon-minus
                    playlist
                %br
                %small
                  = Time.at((subtitle.end_at||subtitle.video.duration) - subtitle.start_at).utc.strftime("%H:%M:%S")
                %br
                %small
                  =subtitle.title
                  =link_to edit_admin_video_subtitle_path(subtitle.video, subtitle) do
                    %span.glyphicon.glyphicon-edit
                  %br
                  = link_to video_path(subtitle.video) do
                    %span.glyphicon.glyphicon-film
                    = subtitle.video.title
          - if (index+1)%3==0
            .clearfix

app/views/playlists/index.html.haml
%h3.page-title Playlists

.row
  - @playlists.each do |playlist|
    - if playlist.plays.count > 0
      .col-sm-6
        = render playlist
        %p
          = playlist.plays.collect{|p| p.playable}.map(&:title).join(',')

app/views/playlists/show.html.haml
%h3.page-title PLAYLIST
%h4 #{@playlist.name}
- if @playlist.plays.count > 0
  - #ActiveModel::Serializer.serializer_for(@playlist.plays.map(&:playable)).new(@playlist.plays.map(&:playable)).to_json
  - plays = @playlist.plays.shuffle
  :javascript
    var subtitles = #{plays.map(&:playable).to_json};
    var videos = #{plays.map(&:video).to_json};
    var current_subtitle_index = null;
    var currentPlay = null;
    var start_at = 0;
    var repeat = false

    var seekToVideo = function seekToVideo(index, rep){
      repeat = rep
      
      var subtitle = $('#subtitle_' + index);
      current_subtitle_index = index;
      currentSubtitle = subtitles[index];


      var player = $('#movie').get(0);
      var source = $('source', player);

      if ($(source).attr('src')!=videos[index].file.url){
        $(source).attr('src', videos[index].file.url);
        player.load();
        player.play();
      }
      
      $('#movie').get(0).currentTime = currentSubtitle.start_at;

      updateCurrentSubtitleHtml(currentSubtitle);
      $('.repeat .text').html('');
      if(rep){
        $('.repeat .text', subtitle).html('<small>repeating...</small>');
      }else{
        $('.repeat .text', subtitle).html('');
      }
    }

    var updateCurrentSubtitleHtml = function(subtitle){
      if(subtitle){
        $('#subtitle').html(subtitle.title);
        if(subtitle.description){
          var description = subtitle.description.replace(/(?:\r\n|\r|\n)/g, '<br />')
          $('#description').html(description);
        }else{
          $('#description').html('');
        }
      }
    }

    $(function(){
      var movie = $('#movie').get(0);
      var video = $('#movie').get(0);
      for(var i=0;i<subtitles.length;i++){
        subtitles[i].end_at = subtitles[i].end_at || videos[i].duration - 5;
      }

      $(movie).bind('timeupdate', function() {
        if (currentSubtitle){
          if (movie.currentTime > currentSubtitle.start_at && movie.currentTime > currentSubtitle.end_at && !repeat){
            seekToVideo((current_subtitle_index + 1)%subtitles.length, false);
          }
        }

        if(currentSubtitle && movie.currentTime > currentSubtitle.end_at && repeat==true){
          movie.currentTime = currentSubtitle.start_at;
        }
      })

      // display comments at start
      $('.thread a').trigger('click');

      // seek when press arrow keys
      var frameTime = 5;
      window.addEventListener('keydown', function (evt) {
        if (true) { //or you can force it to pause here
            if (evt.keyCode === 32) { //left arrow
              movie.pause();
              evt.preventDefault();
              return;
            }

            if (evt.keyCode === 37) { //left arrow
                if (movie.currentTime > 0) {
                    //one frame back
                    movie.currentTime -= frameTime;
                }
            } else if (evt.keyCode === 39) { //right arrow

                if (movie.currentTime < movie.duration) {
                    //one frame forward
                    //Don't go past the end, otherwise you may get an error
                    movie.currentTime = Math.min(movie.duration, movie.currentTime + frameTime);
                }
            }
        }
      });
      
      // play first video as default
      seekToVideo(0, false);
    });
  .row
    .col-sm-6
      %video#movie{:controls => "", :height => "auto", :poster => @playlist.plays.first.playable.thumbnail.url, :preload => "none", :width => "100%", :autoplay=> true}
        %source{:src => '', :type => "video/mp4"}

      %h4#subtitle
        =@subtitle.try(:title)
      #description
        = sanitize(simple_format(@subtitle.try(:description)))  
    .col-sm-6
      .row
        - plays.map(&:playable).each_with_index do |subtitle, index|
          .col-md-4.col-sm-4.col-xs-4
            %div{ id: "subtitle_#{index}"}
              %p
                = link_to "#title", onclick: "seekToVideo(#{index}, false);" do
                  = image_tag subtitle.thumbnail.thumb.url, class: 'img-responsive'
              %p.text-center
                =link_to '#title', onclick: "seekToVideo(#{index}, !repeat);", class: 'repeat btn btn-xs' do
                  %span.glyphicon.glyphicon-repeat
                  %span.text
                - if current_user && current_user.playlist.plays.include?(subtitle.play)
                  =link_to play_path(subtitle.play), method: :delete do
                    %span.glyphicon.glyphicon-minus
                    playlist
                %br
                %small
                  = Time.at((subtitle.end_at||subtitle.video.duration) - subtitle.start_at).utc.strftime("%H:%M:%S")
                %br
                %small
                  =subtitle.title
                  =link_to edit_admin_video_subtitle_path(subtitle.video, subtitle) do
                    %span.glyphicon.glyphicon-edit
                  %br
                  = link_to video_path(subtitle.video) do
                    %span.glyphicon.glyphicon-film
                    = subtitle.video.title
          - if (index+1)%3==0
            .clearfix
- else
  .alert.alert-warning
    Sorry, you don't have any playable videos in your playlist, please add some subtitles.
%br
%br
%h3.page-title Other user's playlists
%table.table.table-striped
  - Playlist.all.each do |playlist|
    -if playlist != current_user.try(:playlist) && playlist.plays.count > 0
      %tr
        %td.col-sm-2
          = link_to playlist_path(playlist) do
            = image_tag playlist.plays.first.playable.thumbnail_url, class: 'img-responsive'
        %td
          = link_to playlist_path(playlist) do
            %span.glyphicon.glyphicon-play
            = playlist.name
        %td
          = playlist.plays.map(&:playable).map(&:title).join(' ,')
        %td
          = playlist.user.try(:full_name)
          %br
          = playlist.user.try(:email)