config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Commontator::Engine => '/commontator'
  namespace :admin do
    resources :videos do
      resources :subtitles
      member do
        patch :encode
      end
      collection do
        get :featured
      end
    end
    resources :categories
    resources :photos do
      collection do
        get :featured
      end
    end
  end

  resources :categories, only: [:show] do
    member do
      get :tag
    end

    resources :videos, only: [:index]
  end

  resources :videos, only: [:show, :index] do
    collection do
      get :search
      get :most_viewed
      get :most_scored
      get :most_voted
    end
    member do
      get :download
      get :tag
      get :wide
      get :embed
      put "like", to: "videos#upvote"
      put "dislike", to: "videos#downvote"
      post :favorite
      post :unfavorite
      post :capture_photo
    end
  end

  resources :favorites, only: [:index]

  resources :subtitles do
    member do
      get :tag
      post :add_to_playlist
      post :remove_from_playlist
    end
  end

  resources :playlists do
    member do
      get :embed
    end
  end
  resources :plays
  resources :photos do
    member do
      get :tag
    end
    collection do
      get :search
      get :featured
    end
  end
  
  resources :users do
    member do
      get :photos
      get :videos
    end
  end

  get '/admin', to: 'admin/videos#index', as: 'admin_root'
  root to: "homes#index"
end

app/models/video.rb
require "redis"
class Video < ActiveRecord::Base
  acts_as_taggable
  acts_as_commontable
  acts_as_votable

  markable_as :favorite
  
  is_impressionable counter_cache: true
  
  mount_uploader :file, VideoFileUploader
  mount_uploader :thumbnail, VideoThumbnailUploader
  scope :recent, ->{ order(created_at: :desc) }
  scope :most_viewed, ->{ order('impressions_count DESC') }
  scope :most_scored, ->{ order('votes_score DESC') }
  scope :most_voted, ->{ order('upvotes_count DESC') }
  scope :featured, ->{ where(featured: true) }
  scope :encoded, ->{ where.not(status: 'encoding') }

  has_many :subtitles, -> { order('start_at ASC') }, dependent: :destroy
  belongs_to :category
  belongs_to :user
  has_one :play, as: :playable

  has_many :photos
  after_create :encode_video_file

  validates_presence_of :title

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  def update_meta_tags
    tags = self.tag_list || []
    tags << self.category.try(:name)
    self.meta_tags = (self.subtitles.map(&:title) + tags).join(', ')
    self.save
  end

  def refresh_metadata
    movie = FFMPEG::Movie.new(self.file.path)
    self.duration = movie.duration
    self.width = movie.width
    self.height = movie.height
    self.thumbnail = movie.screenshot("tmp/thumbnail-#{self.id}-#{seconds}.jpg", :seek_time => 10)
    self.save
  end

  def screen_shot_at(seconds)
    movie = FFMPEG::Movie.new(self.file.path)
    movie.screenshot("tmp/thumbnail-#{self.id}-#{seconds}.jpg", :seek_time => seconds)
  end

  def encoding_progress
    redis = Redis.new
    redis.get("video_encoding_progress_#{self.id}")
  end

  def self.encode(id)
    video = Video.find(id)
    if !video.playable? and video.status!='encoding'
      video.status = 'encoding'
      video.save

      movie = FFMPEG::Movie.new(video.file.path)
      file_extension = File.extname(video.file.path)
      file_name = File.basename(video.file.path, file_extension)
      new_file_name = "tmp/#{file_name}-#{Time.now.to_s(:number)}.mp4"
      redis = Redis.new
      video.file = movie.transcode(new_file_name) do |progress|
        redis.set("video_encoding_progress_#{id}", progress)
        puts progress
      end
      video.status = 'encoded'
      video.save
    end
  end

  def playable?
    if self.status=='encoding'
      return false
    elsif self.status=='encoded'
      return true
    end

    return false if !self.file?

    black_list = ['.vob', '.flv', '.ts']
    white_list = ['.mp4', '.m4v', '.webm', '.ogg', '.mov']
    return false unless white_list.include? File.extname(self.file.path).downcase

    movie = FFMPEG::Movie.new(self.file.path)
    codec = movie.video_codec || ""
    return true if codec.include?('h264')
    return false
  end

  def encode_video_file
    unless self.playable?
      Video.delay_for(10.seconds).encode(self.id)
    end
  end

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'description', 'meta_tags']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            title: {},
            description: {},
            meta_tags: {}
          }
        }
      }
    )
  end

end

Video.import

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_filter :set_video, only: [:edit, :update, :destroy, :encode]

  def index
    @videos = Video.recent.page(params[:page])
  end

  def new
    @video = Video.new
  end

  def tag
  end

  def featured
    @videos = Video.featured.recent.page(params[:page])
    render :index
  end

  def edit
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    if @video.save
      flash[:success] = "Created a video successfully."
      redirect_to admin_videos_path
    else
      render :edit
    end
  end

  def update
    if @video.update_attributes(video_params)
      flash[:success] = "Updated a video successfully."
      redirect_to edit_admin_video_path(@video)
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    flash[:success] = "Deleted a video successfully."
    redirect_to admin_videos_path
  end

  def encode
    flash[:success] = "Started to encode a video successfully. Wait several minutes."
    Video.delay.encode(@video.id)
    redirect_to edit_admin_video_path(@video)
  end

  private
  def video_params
    params.require(:video).permit(:title, :description, :file, :thumbnail, :tag_list, :category_id, :featured)
  end

  def set_video
    @video = Video.find(params[:id])
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :set_category, :set_most_viewed
  impressionist :actions=>[:show]

  before_filter :set_sort_and_filter
  before_filter :set_subtitle

  before_filter :authenticate_user!, only: [:favorite, :unfavorite]
  layout :set_wide_layout, only: [:wide]

  def show
    @video = Video.find(params[:id])
    @video.impressions_count = @video.impressionist_count
    @video.save
  end
  
  def tag_cloud
    @tags = Video.tag_counts_on(:tags)
  end

  def index
    if !params[:tag].blank?
      @videos = Video.tagged_with(params[:tag])
    else
      if @sort_by
        @videos = Video.order("#{@sort_by} #{@sort_direction}")
      else
        @videos = Video.recent
      end
    end

    @videos = @videos.where(category_id: @category.id) if !@category.blank?
    @videos = @videos.where("created_at >= ?", @start_date) if @start_date
    @videos = @videos.where("created_at <= ?", @end_date) if @end_date
    @videos = @videos.page(params[:page]).per(12)
  end

  def search
    @videos = Video.search(params[:search])
    @videos = @videos.page(params[:page])
  end

  def most_viewed
    @title = "Most viewed"
    @videos = Video.most_viewed.page(params[:page])
    render :index
  end

  def most_voted
    @title = "Recommended"
    @videos = Video.most_voted.page(params[:page])
    render :index
  end

  def most_scored
    @title = "Top videos"
    @videos = Video.most_scored.page(params[:page])
    render :index
  end

  def tag
    @videos = Video.tagged_with(params[:id])
    @videos = @videos.order("#{@sort_by} #{@sort_direction}") if @sort_by
    @videos = @videos.page(params[:page])
    @tag = params[:id]
    render :index
  end

  def download
    @video = Video.find(params[:id])
    redirect_to @video.file.url
  end

  def upvote
    @video = Video.find(params[:id])
    @video.upvote_by current_user
    @video.upvotes_count = @video.get_upvotes.count
    @video.votes_score = @video.upvotes_count - @video.downvotes_count
    @video.save
    redirect_to video_path(@video)
  end

  def downvote
    @video = Video.find(params[:id])
    @video.downvote_by current_user
    @video.downvotes_count = @video.get_downvotes.count
    @video.votes_score = @video.upvotes_count - @video.downvotes_count
    @video.save
    redirect_to video_path(@video)
  end

  def favorite
    @video = Video.find(params[:id])
    current_user.favorite_videos << @video
    current_user.save
    flash[:success] = "Added a video to favorites successfully."
    if params[:redirect]
      redirect_to params[:redirect]
    else
      redirect_to video_path(@video)
    end
  end

  def unfavorite
    @video = Video.find(params[:id])
    current_user.favorite_videos.delete @video
    flash[:success] = "Removed a video from favorites successfully."

    if params[:redirect]
      redirect_to params[:redirect]
    else
      redirect_to video_path(@video)
    end
  end

  def wide
    @video = Video.find(params[:id])

  end

  def set_wide_layout
    'wide'
  end

  def capture_photo
    @video = Video.find(params[:id])
    if !params[:video_at].blank?
      @photo = Photo.new
      @photo.file = @video.screen_shot_at(params[:video_at].to_f)
      @photo.title = "#{@video.title} #{Time.now.to_f}"
      @photo.video_at = params[:video_at].to_i
      @photo.video = @video
      @photo.user = current_user
      @photo.save

      redirect_to edit_admin_photo_path(@photo)
    else
      redirect_to :back
    end
  end

  def embed
    @video = Video.find(params[:id])
    render :embed, layout: 'embed'
  end

  private
  def set_category
    @category = Category.find(params[:category_id]) rescue nil
  end

  def set_most_viewed
    @most_viewed = Video.order('impressions_count DESC').take(10)
  end

  def set_sort_and_filter
    @sort_by = params[:sort_by]
    @sort_direction = params[:sort_direction] || 'desc'

    @start_date = Time.parse(params[:start_date]) rescue nil
    @end_date = Time.parse(params[:end_date]) rescue nil
  end

  def set_subtitle
    @subtitle = Subtitle.find(params[:subtitle_id]) if params[:subtitle_id]
  end
end

app/views/admin/videos/_form.html.haml
.row
  .col-md-6
    %h4 #{@video.title}
    .well
      = bootstrap_form_for [:admin, @video], layout: :horizontal do |f|
        = f.file_field :file, label: 'Video'

        - if @video.file?
          = f.form_group do
            = File.basename(@video.file.url)

        = f.file_field :thumbnail, label: 'Thumbnail'
        = f.form_group do
          = image_tag(@video.thumbnail.thumb.url) if @video.thumbnail?
          = f.check_box :remove_thumbnail
        = f.text_field :title
        = f.text_area :description, rows: 6
        = f.select :category_id, [''] + nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }
        = f.text_field :tag_list, value: f.object.tag_list.to_s

        = f.form_group do
          = f.check_box :featured
        = f.form_group do
          = f.submit "Submit", class: 'btn btn-primary', data: { :disable_with => "Please Wait..." }
          - if !@video.new_record?
            = link_to "Delete", admin_video_path(@video), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" }
            = link_to "Show", video_path(@video), class: 'btn btn-info'
            - if !@video.playable?
              = link_to "Encode", encode_admin_video_path(@video), class: 'btn btn-warning', method: :patch
              = "#{@video.encoding_progress}% encoded"

  .col-md-6
    - if @video.file?
      .row
        .col-sm-12
          %h4 New Subtitle
          .well
            = bootstrap_form_for [:admin, @video, @video.subtitles.new], layout: :horizontal do |f|
              = f.form_group do
                %video#movie{:controls => "", :height => "auto", :poster => @video.thumbnail.url, :preload => "none", :width => "100%", :autoplay=> true}
                  %source{:src => @video.file.url, :type => "video/mp4"}
                %p
                  = link_to "Capture subtitle position", "javascript: void(0); captureSubtitlePosition();", class: "btn btn-primary"
                  = link_to "Clear subtitle positions", "javascript: void(0); clearNewSubtitlePositions();", class: "btn btn-danger"
              = f.text_field :title, label: 'Title *'
              = f.text_field :start_at, id: "subtitle_start_at", label: 'Start at *'
              = f.text_field :end_at, id: "subtitle_end_at", help: "Optional, and we will use next subtitle's start_at"
              = f.form_group do
                = f.submit "Submit", class: 'btn btn-primary', data: { :disable_with => "Please Wait..." }

%hr

%h4 Other subtitles in this video
.row
  - @video.subtitles.each do |subtitle|
    - unless subtitle.new_record?
      .col-md-2.col-sm-3
        .well
          = link_to "#movie", onclick: "seekToVideo(#{subtitle.start_at});" do
            = image_tag subtitle.thumbnail.thumb.url, class: 'img-responsive'
          = subtitle.title
          ,
          = subtitle.start_at
          = link_to 'Edit', edit_admin_video_subtitle_path(@video, subtitle), class: 'btn btn-info btn-sm'
%br
%br

- @subtitle ||= Subtitle.find(params[:subtitle_id]) rescue nil
:javascript
  function captureSubtitlePosition(){
    $('#movie').get(0).pause();
    if($('#subtitle_start_at').val())
    {
      $('#subtitle_end_at').val($('#movie').get(0).currentTime);
    }else{
      $('#subtitle_start_at').val($('#movie').get(0).currentTime);
    } 
  }

  function clearNewSubtitlePositions(){
    $('#subtitle_start_at').val('');
    $('#subtitle_end_at').val('');
  }

  function seekToVideo(start_at){
    $('#movie').get(0).currentTime = start_at;
  }

  $(function(){
    var movie = $('#movie').get(0);
    movie.currentTime = "#{@subtitle.try(:start_at) rescue 0}";
    // seek when press arrow keys
    var frameTime = 5;
    window.addEventListener('keydown', function (evt) {
      if (true) { //or you can force it to pause here
          if (evt.keyCode === 37) { //left arrow
              if (movie.currentTime > 0) {
                  //one frame back
                  movie.currentTime -= frameTime;
              }
          } else if (evt.keyCode === 39) { //right arrow

              if (movie.currentTime < movie.duration) {
                  //one frame forward
                  //Don't go past the end, otherwise you may get an error
                  movie.currentTime = Math.min(movie.duration, movie.currentTime + frameTime);
              }
          }
      }
    });
  });
  
  

app/views/admin/videos/edit.html.haml
%h2 Edit Video
= render 'form'

app/views/admin/videos/index.html.haml
%h2 Videos (#{Video.count})

%p.clearfix
  = link_to "All videos", admin_videos_path
  |
  = link_to "Featured videos", featured_admin_videos_path
  = link_to "Post New Video", new_admin_video_path, class: 'btn btn-primary pull-right'

.clearfix
  = paginate @videos

%table.table
  %thead
    %th
    %th Title
    %th Playable?
    %th Category
    %th Tags
    %th Descrition
    %th 
  - @videos.each do |video|
    %tr{class: "#{"alert alert-info" if video.featured?}"}
      %td.col-sm-1
        - if video.thumbnail?
          = image_tag video.thumbnail.thumb.url, class: "img-responsive"
        - else
          = image_tag asset_path('no-thumbnail.png'), class: "img-responsive"
      %td=video.title
      %td
        - if video.playable?
          %span.glyphicon.glyphicon-play
        - else
          %span.glyphicon.glyphicon-remove
          %br
          = "#{video.encoding_progress}% encoded"
      %td
        = video.category.try(:name)
      %td
        = video.tag_list
      %td.col-sm-2
        = sanitize(truncate(video.description, :omission => "...", :length => 40))
      %td
        = link_to edit_admin_video_path(video), class: "btn btn-info btn-sm" do
          %span.glyphicon.glyphicon-pencil
          Edit
        = link_to video_path(video), class: "btn btn-info btn-sm" do
          %span.glyphicon.glyphicon-eye-open
          Show
        = link_to admin_video_path(video), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" } do
          %span.glyphicon.glyphicon-trash
          Delete
.clearfix
  = paginate @videos

app/views/admin/videos/new.html.haml
%h2 New Video
= render 'form'